/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ElEMENTS.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ElEMENTS.glb');
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.003']} rotation={[0, 1.28, 0]} scale={[0.23, 0.1, 0.23]} />
    </group>
  )
}

useGLTF.preload('/ElEMENTS.glb')
